name: lovo_robot_bridge
from_domain: 70
to_domain: 61

topics:
  # Domain 70 → 61 (PC → Robot)
  /robot2/target_angles:
    type: std_msgs/msg/Float64MultiArray
    from_domain: 70
    to_domain: 61
    remap: /target_angles

  /robot2/servo_status:
    type: std_msgs/msg/Bool
    from_domain: 70
    to_domain: 61
    remap: /servo_status

  /robot2/gripper_control:
    type: std_msgs/msg/Int32
    from_domain: 70
    to_domain: 61
    remap: /gripper_control

  /robot2/target_coords:
    type: std_msgs/msg/Float64MultiArray
    from_domain: 70
    to_domain: 61
    remap: /target_coords

  # Domain 61 → 70 (Robot → PC)
  /current_angles:
    type: std_msgs/msg/Float64MultiArray
    from_domain: 61
    to_domain: 70
    remap: /robot2/current_angles

  /current_coords:
    type: std_msgs/msg/Float64MultiArray
    from_domain: 61
    to_domain: 70
    remap: /robot2/current_coords
